version: '2'
services:
  web:
    image: portainer/portainer
    ports:
      - '9999:9000'
    command: '-H unix:///var/run/docker.sock'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
volumes:
  portainer_data: null
